// Code generated by "stringer -type=Rabbit"; DO NOT EDIT.

package rabbits

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Alaska-0]
	_ = x[Altex-1]
	_ = x[American-2]
	_ = x[Angora-3]
	_ = x[Astrex-4]
	_ = x[Bauscat-5]
	_ = x[Brazilian-6]
	_ = x[Beveren-7]
	_ = x[Pygmy-8]
	_ = x[Cottontail-9]
}

const _Rabbit_name = "AlaskaAltexAmericanAngoraAstrexBauscatBrazilianBeverenPygmyCottontail"

var _Rabbit_index = [...]uint8{0, 6, 11, 19, 25, 31, 38, 47, 54, 59, 69}

func (i Rabbit) String() string {
	if i < 0 || i >= Rabbit(len(_Rabbit_index)-1) {
		return "Rabbit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rabbit_name[_Rabbit_index[i]:_Rabbit_index[i+1]]
}
